// Second FAQ entries, merged into the service by id.
export const faqExtra = {
  "38": ["Was passiert mit unseren alten Angeboten und Rechnungen?", "Die bleiben, wo sie sind, und werden archiviert. Kundendaten übernehmen wir, damit neue Angebote direkt im neuen Tool entstehen."],
  "42": ["Können Patientinnen und Patienten den Bogen schon zu Hause ausfüllen?", "Ja, auf Wunsch vorab online per Link. In der Praxis geht es am Tablet."],
  "49": ["Kann der ganze Vorstand darauf zugreifen?", "Ja, mit Rechten je Rolle. Wer ausscheidet, wird sauber ausgetragen, ohne dass Daten verloren gehen."],
  "50": ["Bekommen Spender eine Quittung?", "Viele Spendenplattformen erstellen Zuwendungsbestätigungen. Was steuerlich gilt, klärt eure Steuerberatung."],
  "60": ["Wo wird der Podcast gehostet?", "Bei einem Podcast-Hoster deiner Wahl. Das Konto läuft auf dich, damit du jederzeit wechseln kannst."],
  "61": ["Was passiert bei Absagen?", "Wir richten die Regeln für Absage und Erstattung so ein, wie du sie festlegst, und testen sie vorher."],
  "72": ["Wer bedient den Livestream?", "Dein Team. Das Set ist so einfach gehalten, dass es nach der Einweisung ohne Technikkenntnisse läuft."],
  "83": ["Welche Kameras unterstützt ihr?", "Gängige Mobilfunk-Wildkameras. Nenn uns dein Modell vor der Zahlung, dann prüfen wir es."],
  "84": ["Können Einsteller ihre Rechnungen online sehen?", "Ja, wenn die gewählte Software das anbietet. Wir richten den Zugang für Einsteller mit ein."],
  "85": ["Bekommen Fahrschüler eine Erinnerung vor der Stunde?", "Ja, Erinnerungen per SMS oder WhatsApp lassen sich in die Buchung einbauen."],
  "86": ["Was passiert, wenn nachts etwas klemmt?", "Du bekommst Alarme aufs Handy und einen Notfallplan. Ein nächtlicher Bereitschaftsdienst ist nicht enthalten."],
  "87": ["Brauche ich eine Kasse mit TSE?", "Das hängt von deinem Betrieb ab und ist eine steuerliche Frage. Kläre sie mit deiner Steuerberatung; wir richten die Technik passend ein."],
  "55": ["Wie viel spare ich?", "Das hängt von deinen Abos ab. Im Bericht steht die geschätzte jährliche Einsparung für jedes Abo, das du kündigen oder herunterstufen kannst."],
  "57": ["Wohin ziehen die Daten?", "In ein System, das zu deinen Abläufen passt, etwa Airtable oder eine Branchenlösung. Wir empfehlen nach der Analyse."],
  "58": ["Wie groß darf der Umzug sein?", "Der Festpreis gilt für einen üblichen Umzug eines kleinen Betriebs. Bei großen Datenmengen nennen wir den Preis vor der Zahlung."],
  "81": ["Müssen wir Fachsoftware wechseln?", "Nein. Es geht um Dateien und Kalender. Fachsoftware bleibt, wie sie ist."],
  "82": ["Was passiert mit Kontakten, die noch faxen?", "Für eine Übergangszeit lässt sich ein Fax-Eingang digital empfangen, bis alle umgestellt sind."],
  "19": ["Wie lange dauert es?", "72 Stunden, sobald Zahlung und Fotos da sind."],
  "FT": ["Brauche ich KI-Kenntnisse?", "Nein. Du schickst Fotos und Infos, wir liefern fertige Inhalte."],
  "37": ["Können mehrere Mitarbeitende antworten?", "Ja, WhatsApp Business lässt sich auf mehreren Geräten nutzen. Wir richten das mit ein."],
  "41": ["Was passiert mit Terminen, die telefonisch kommen?", "Die trägst du oder dein Team einfach in dasselbe System ein. So bleibt ein Kalender die Wahrheit."],
  "43": ["Wie schnell kommen mehr Bewertungen?", "Das hängt davon ab, wie viele Kundinnen und Kunden du hast und wie konsequent dein Team fragt. Das System macht das Fragen einfach."],
  "44": ["Kann ich Preise selbst ändern?", "Ja, ohne Technikkenntnisse. Wir zeigen dir, wie."],
  "46": ["Was ist ein Channel-Manager?", "Ein Tool, das Kalender und Preise zwischen Airbnb, Booking.com und anderen Plattformen abgleicht. Wird ein Zeitraum gebucht, ist er überall blockiert."],
  "47": ["Wie schnell wirkt das?", "Änderungen sind sofort sichtbar. Wie sich Buchungen entwickeln, hängt auch von Saison und Bewertungen ab."],
  "80": ["Dürfen wir Mitarbeitende um Bewertungen bitten?", "Ja, wenn die Bitte freiwillig ist und niemand vorgibt, was drinsteht. Genau so richten wir den Ablauf ein."],
  "63": ["Wann bekomme ich das Ergebnis?", "In 48 Stunden, sobald Zahlung und Fragebogen da sind."],
  "64": ["Welche Plattformen sind relevant?", "Das hängt von Region und Gewerk ab. In Sachsen sind andere Portale wichtig als in Bayern. Wir wählen nach deinem Profil."],
  "69": ["Wann sollte ich damit anfangen?", "Am besten ein bis zwei Jahre vor der Übergabe. Dann bleibt Zeit, gefundene Risiken in Ruhe zu beheben."],
  "70": ["Was, wenn der Vorgänger keine Zugänge übergeben hat?", "Dann holen wir sie über die offiziellen Wege der Anbieter zurück, mit Nachweis, dass der Betrieb jetzt dir gehört."],
  "89": ["Arbeitet ihr auf Bengali?", "Ja. Deutsch, Englisch und Bengali."],
  "90": ["In welchen Sprachen?", "Deutsch und Englisch als Standard, Bengali auf Anfrage. Weitere Sprachen prüfen wir vor der Zahlung."],
  "28": ["Wie oft sollte ich das prüfen lassen?", "Nach jeder größeren Änderung an der Website und sonst einmal im Jahr. Als laufende Website-Pflege geht es auch monatlich."],
  "59": ["Brauche ich GA4 überhaupt?", "Nicht zwingend. Wenn du lieber ein datensparsames Tool willst, sprechen wir vorher darüber."],
  "31": ["Kommt ihr zu uns nach Hause?", "In Chemnitz und Umgebung ja. Sonst richten wir es per Fernhilfe ein."],
  "32": ["Muss jeder in der Familie mitmachen?", "Am besten ja. Jede Person bekommt einen eigenen Tresor im Passwortmanager; geteilte Passwörter liegen in einem gemeinsamen."],
  "33": ["Wie viele Fotos sind enthalten?", "Der Festpreis gilt für eine übliche Familienmenge. Bei sehr großen Sammlungen nennen wir den Preis vor der Zahlung."],
  "34": ["Wie lange dauert es?", "Die Vorsorge ein bis zwei Wochen. Bei Hinterbliebenen hängt es von den Bearbeitungszeiten der Anbieter ab."],
  "35": ["Was passiert mit dem alten Gerät?", "Auf Wunsch löschen wir es sicher, damit du es verkaufen oder verschenken kannst."],
  "65": ["Welche Förderungen gibt es?", "Das ändert sich. Wir prüfen beim Termin, was aktuell für dich in Frage kommt, und zeigen dir den Antragsweg. Eine Förderung können wir nicht zusagen."],
  "71": ["Wie lange dauert es?", "Etwa zwei Wochen, je nach Menge. Den genauen Zeitraum nennen wir nach der Sichtung."],
  "74": ["Was brauche ich dafür?", "Ein Foto vom Typenschild des Wechselrichters und der Module, das Datum der Inbetriebnahme und die Zählernummer."],
  "75": ["Wer meldet die Anlage beim Netzbetreiber?", "Meist der Installationsbetrieb. Hat der das nicht erledigt, unterstützen wir dich dabei."],
  "76": ["Muss ich das jedes Jahr machen?", "Ja, die Quote wird jährlich beantragt. Wir erinnern dich im nächsten Jahr."],
  "77": ["Wie viel spare ich?", "Das hängt von deinem Verbrauch und den Strompreisen ab. Wir zeigen dir, wo du die Ersparnis siehst, versprechen aber keinen Betrag."]
};
