import { defineCollection } from 'astro:content';
import { glob, file } from 'astro/loaders';
import { serviceSchema, catalogRowSchema, categorySchema, sectorSchema, momentSchema } from './lib/schemas.ts';

// Public content, generated by scripts/build-content.ts and editable by hand.
const services = defineCollection({
  loader: glob({ pattern: '*.json', base: './src/content/services', generateId: ({ data }) => String(data.id) }),
  schema: serviceSchema
});
const catalog = defineCollection({ loader: file('src/content/catalog.json'), schema: catalogRowSchema });
const categories = defineCollection({ loader: file('src/content/categories.json'), schema: categorySchema });
const sectors = defineCollection({ loader: file('src/content/sectors.json'), schema: sectorSchema });
const moments = defineCollection({ loader: file('src/content/moments.json'), schema: momentSchema });

export const collections = { services, catalog, categories, sectors, moments };
